### ISSUE TITLE
on the 20th, and the update has broken all build pipelines that use this task ms-devlabs.utilitytasks.task-Shellpp.Shell++@0

### ISSUE THREAD

**Issue by BrianMouncer** [microsoft/Extension-UtilitiesPack#8]
The issue is that this task was auto updated in our ADO on the 20th, and the update has broken all build pipelines that use this task.  error, "A task is missing. The pipeline references a task called 'ms-devlabs.utilitytasks.task-Shellpp.Shell++'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com."   However, I have verified the task is still installed in our ADO org, it was auto-updated from 0.1.10 to 0.1.11 the day to pipelines started failing.  Can you investigate what package changes in 0.1.11 have broken Shell++ task availability.

**Comment by BrianMouncer** [comment]
Per response to my vs market place support q&a question, I changed all references to "ms-devlabs.utilitytasks.task-Shellpp.Shell++@0" into "ms-devlabs.utilitytasks.task-Shellpp.Shellpp@0"

and builds are at least starting now, rather that failing to even start due to missing installed ado tasks.

**Comment by MOlausson** [comment]
Thanks @BrianMouncer for sharing this. Since the resolution was to update the name I will close this issue. The underlying problem was due to a very old change in name of the task that for some reason didn't manifest until we made the most recent change.
